<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => '',
    'Home' => '',
    'Status' => '',
    
    //Nuevos
    'Wallet Address' => 'Dirección Billetera',
    'Country' => 'País',
    'Sponsor' => 'Patrocinador',    
    'Affiliate Network' => 'Red de Afiliados',
    'Memberships' => 'qqqqqqqqqqqq',
    'Commissions' => 'sssssssssssssss',
    'Reports' => '11111111111111',
    'MAIN NAVIGATION' => 'MENÚ DE NAVEGACIÓN',
    'Please fill out the following fields to signup' => 'Por favor rellena los siguientes campos para registrarte',
    'If you forgot your password you can' => 'Si olvidaste tu contraseña puedes',
    'Restore Password' => 'Reestablecer Contraseña',
    'Update Your Information' => 'Actualiza tus Datos',
    'Join WeiFastPay' => 'UNIRSE A WEIFASTPAY',
    'Thank you for your desire to enter WeiFastPay. Soon you will know, it will be one of the best decisions of your life!' => 'Gracias por tu deseo de ingresar a WeiFastPay. Pronto sabrás, que será una de las mejores decisiones de su vida!'

];
