<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Около',
    'Home' => 'Главная',
    'Status' => 'Статус',
    
    // models
    'ID' => 'Номер',
    'User ID' => 'Номер пользователя',
    'Created At' => 'Дата создания',
    'Updated At' => 'Дата обновления',
    'Full Name' => 'Полное имя',

    'Name' => 'Имя',
    'Can Admin' => 'Имеет права админа',

    'Role' => 'Роль',
    'Role ID' => 'Номер роли',
    'Status' => 'Статус',
    'Email' => 'E-mail адрес',
    'New Email' => 'Новый E-mail адрес',
    'Username' => 'Логин пользователя',
    'Password' => 'Пароль',
    'Auth Key' => 'Ключ авторизации',
//    'Access Token' => '',
    'Logged In Ip' => 'IP авторизации',
    'Logged In At' => 'Дата авторизации',
    'Created Ip' => 'IP создания',
    'Banned At' => 'Дата бана',
    'Banned Reason' => 'Причина бана',
    'Current Password' => 'Текущий пароль',
    'New Password' => 'Новый пароль',    
    
    'Password Repeat' => 'Пароль Повторите',
    'Access Token' => 'Токен доступа',    
    'New Password Confirm' => 'Новый пароль Подтверждение',
    
    'Email Confirmation' => 'E-mail подтверждение',
    
    'Provider' => 'Приглашение',
    'Provider ID' => 'Номер пользователя который пригласил',
    'Provider Attributes' => 'Атрибуты приглашения',
    

    'Type' => 'Тип',
    'Token' => 'Token',
    'Expired At' => 'Срок действия',

    // models/forms
    'Email not found' => 'E-mail не найдено',
    'Email / Username' => 'E-mail / имя пользователя',
    'Email / Username not found' => 'E-mail / имя пользователя не найдено',
    'Username not found' => 'Пользователь не найден',
    'User is banned - {banReason}' => 'Пользователя блокировано - {banReason}',
    'Incorrect password' => 'Неверный пароль',
    'Remember Me' => 'Запомнить меня',
    'Email is already active' => 'E-mail уже активен',
    
    'Passwords do not match' => 'Пароли не совпадают',
    '{attribute} can contain only letters, numbers, and "_"' => '{attribute} может содержать только буквы, цифры, и "_"',

    // controllers
    'Successfully registered [ {displayName} ]' => 'Успешно зарегистрирован [ {displayName} ]',
    ' - Please check your email to confirm your account' => ' - Проверьте свою почту, чтобы подтвердить свой ​​аккаунт',
    'Account updated' => 'Дата обновления аккаунта',
    'Profile updated' => 'Дата обновления профиля',
    'Confirmation email resent' => 'Подтверждение по электронной почте отправлено заново',
    'Email change cancelled' => 'Изменение E-mail отменено',
    'Instructions to reset your password have been sent' => 'Инструкции по изменению вашего пароля, были отправлены в ваш почтовый ящик',

    // mail
   'Please confirm your email address by clicking the link below:' => 'Пожалуйста, подтвердите свой ​​адрес электронной почты, нажав на ссылку ниже:',
    'Please use this link to reset your password:' => 'Пожалуйста, воспользуйтесь этой ссылкой для восстановления пароля:',

    // admin views
    'Users' => 'Пользователи',
    'Banned' => 'Заблокировано',
    'Create' => 'Создано',
    'Update' => 'Обновлено',
    'Delete' => 'Удалено',
    'Search' => 'Поиск',
    'Reset' => 'Сбросить',
    'Create {modelClass}' => 'Создать {modelClass}',
    'Update {modelClass}: ' => 'Изменить {modelClass}: ',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить ваш аккаунт?',

    // default views
     'Account' => 'Аккаунт',
    'Pending email confirmation: [ {newEmail} ]' => 'В ожидании подтверждения по электронной почте: [ {newEmail} ]',
    'Cancel' => 'Отменить',
    'Changing your email requires email confirmation' => 'Изменение электронной почты требует подтверждения нового адреса',
    'Confirmed' => 'Подтверждено',
    'Error' => 'Ошибка',
    'Your email [ {email} ] has been confirmed' => 'Ваш адрес электронной почты [ {email} ] было подтверждено',
    'Go to my account' => 'К моему аккаунту',
    'Go home' => 'На главную',
    'Log in here' => 'Войти сейчас',
     'Invalid Token' => 'Token inválida',
     'Forgot password' => 'Забыли пароль',
    'Submit' => 'Отправить',
    'Yii 2 User' => 'Yii 2 пользователь',
    'Login' => 'Войти',
    'Register' => 'Зарегистрироваться',
    'Logout' => 'Выйти',
    'Resend confirmation email' => 'Повторно отправить подтверждение по электронной почте',
    'Profile' => 'Профиль',
    'Resend' => 'Повторить',
    'Password has been reset' => 'Пароль восстановлено',
    
    //'Login link sent - Please check your email' => '',
    //'Registration link sent - Please check your email' => '',
    
    //Nuevos
    'Wallet Address' => 'Adresse Wallet',
    'Country' => 'Pays',
    'Sponsor' => 'Commanditaire',    
    'Affiliate Network' => 'Affiliate Network',
    'Memberships' => 'Adhésions',
    'Commissions' => 'Commissions',
    'Reports' => 'Rapports',
    'MAIN NAVIGATION' => 'NAVIGATION PRINCIPALE',
    'Please fill out the following fields to signup' => "S'il vous plaît remplir les champs ci-dessous pour vous inscrire",
    'If you forgot your password you can' => 'Si vous avez oublié votre mot de passe, vous pouvez',
    'Restore Password' => 'Restaurer mot de passe',
    'Update Your Information' => 'Mettre à jour vos informations',
    'Join WeiFastPay' => 'Joignez-vous à WEIFASTPAY',
    'Thank you for your desire to enter WeiFastPay. Soon you will know, it will be one of the best decisions of your life!' => "Nous vous remercions de votre désir d'entrer WeiFastPay. Bientôt vous le savez, ce sera l'une des meilleures décisions de votre vie !",
    'Profile'=>'Profil',
    'Dashboard' => 'Tableau de bord',
    'Enter your virtual office' => 'Entrez votre bureau virtuel',
    'Support Center' => 'Centre de soutien',
    'By Levels' => 'Par niveaux',
    'Direct' => 'Direct',
];
