<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => '',
    'Home' => '',
    'Status' => '',
    
    //Nuevos
    'Wallet Address' => 'Wallet Adresse',
    'Country' => 'Land',
    'Sponsor' => 'Sponsor',    
    'Affiliate Network' => 'Affiliate Network',
    'Memberships' => 'Mitgliedschaften',
    'Commissions' => 'Kommissionen',
    'Reports' => 'Berichte',
    'MAIN NAVIGATION' => 'Navegação',
    'Please fill out the following fields to signup' => 'Bitte füllen Sie die folgenden Felder aus um sich anzumelden',
    'If you forgot your password you can' => 'Wenn Sie Ihr Passwort vergessen haben, können Sie',
    'Restore Password' => 'Passwort wiederherstellen',
    'Update Your Information' => 'Aktualisieren Sie Ihre Informationen',
    'Join WeiFastPay' => 'Registriert WEIFASTPAY',
    'Thank you for your desire to enter WeiFastPay. Soon you will know, it will be one of the best decisions of your life!' => 'Vielen Dank für Ihren Wunsch nach WeiFastPay eingeben. Bald werden Sie wissen, wird es eine der besten Entscheidungen Ihres Lebens sein!',
    'Profile'=>'Profil',
    'Dashboard' => 'Armaturenbrett',
    'Enter your virtual office' => 'Geben Sie Ihr virtuelles Büro',
    'Support Center' => 'Support Center',
    'By Levels' => 'Durch die Levels',
    'Direct' => 'Direct',
];
