<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' - Please check your email to confirm your account' => '',
    'Access Token' => '',
    'Account' => '',
    'Account updated' => '',
    'Are you sure you want to delete this item?' => '',
    'Auth Key' => '',
    'Banned' => '',
    'Banned At' => '',
    'Banned Reason' => '',
    'Can Admin' => '',
    'Cancel' => '',
    'Changing your email requires email confirmation' => '',
    'Confirmation email resent' => '',
    'Create' => '',
    'Create {modelClass}' => '',
    'Created At' => '',
    'Created Ip' => '',
    'Current Password' => '',
    'Data' => '',
    'Delete' => '',
    'Dirección de residencia' => '',
    'Dirrecion public monedero bitcoin (si ya lo tienes)' => '',
    'Email' => '',
    'Email Confirmation' => '',
    'Email change cancelled' => '',
    'Email is already active' => '',
    'Email not found' => '',
    'Expired At' => '',
    'Forgot password' => '',
    'Full Name' => '',
    'Go home' => '',
    'Go to my account' => '',
    'ID' => '',
    'Incorrect password' => '',
    'Instructions to reset your password have been sent' => '',
    'Invalid Token' => '',
    'Invalid token' => '',
    'Log in here' => '',
    'Logged In At' => '',
    'Logged In Ip' => '',
    'Login' => '',
    'Name' => '',
    'New Password' => '',
    'New Password Confirm' => '',
    'Nombre Completo' => '',
    'Password' => '',
    'Password has been reset' => '',
    'Passwords do not match' => '',
    'Patrocinador' => '',
    'Pending email confirmation: [ {newEmail} ]' => '',
    'Please confirm your email address by clicking the link below:' => '',
    'Please use this link to reset your password:' => '',
    'Profile' => '',
    'Profile updated' => '',
    'Provider' => '',
    'Provider Attributes' => '',
    'Provider ID' => '',
    'Register' => '',
    'Remember Me' => '',
    'Resend' => '',
    'Resend confirmation email' => '',
    'Reset' => '',
    'Role' => '',
    'Role ID' => '',
    'Search' => '',
    'Status' => '',
    'Submit' => '',
    'Successfully registered [ {displayName} ]' => '',
    'Time zone' => '',
    'Token' => '',
    'Type' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'User ID' => '',
    'User is banned - {banReason}' => '',
    'Username' => '',
    'Users' => '',
    'Usuario' => '',
    'Yii 2 User' => '',
    'Your email [ {email} ] has been confirmed' => '',
    '{attribute} can contain only letters, numbers, and "_"' => '',
];
